"use client";

import { useState, useMemo } from "react";
import { Download, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useApp } from "@/lib/app-context";
import { validateParam } from "@/lib/param-engine";
import type { Param } from "@/lib/types";

interface SaveConfirmModalProps {
  protectedParams: Param[];
  remainingParams: Param[];
  remainingOverrides: Map<string, string>;
  fileName: string | null;
  onConfirm: (header: string | null) => void;
  onClose: () => void;
}

function StatRow({
  value,
  label,
  colorClass,
}: {
  value: number;
  label: string;
  colorClass: string;
}) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="text-sm text-muted-foreground">{label}</span>
      <span className={cn("font-mono text-lg font-bold tabular-nums shrink-0", colorClass)}>
        {value}
      </span>
    </div>
  );
}

export function SaveResumeModal({
  protectedParams,
  remainingParams,
  remainingOverrides,
  fileName,
  onConfirm,
  onClose,
}: SaveConfirmModalProps) {
  const { paramDefs, acknowledgedInvalid, activeListName } = useApp();
  const [includeHeader, setIncludeHeader] = useState(true);

  const invalidCount = useMemo(() => {
    let count = 0;
    for (const p of remainingParams) {
      if (acknowledgedInvalid.has(p.name)) continue;
      const def = paramDefs[p.name];
      if (!def) continue;
      const effectiveValue = remainingOverrides.get(p.name) ?? p.value;
      if (validateParam(effectiveValue, def) !== null) count++;
    }
    return count;
  }, [remainingParams, remainingOverrides, paramDefs, acknowledgedInvalid]);

  const acknowledgedCount = useMemo(
    () => remainingParams.filter((p) => acknowledgedInvalid.has(p.name)).length,
    [remainingParams, acknowledgedInvalid]
  );

  const modifiedCount = remainingOverrides.size;

  const handleDownload = () => {
    let header: string | null = null;
    if (includeHeader) {
      const date = new Date().toISOString().slice(0, 10);
      const invalids: string[] = [];
      const acknowledged: string[] = [];
      for (const p of remainingParams) {
        const def = paramDefs[p.name];
        if (!def) continue;
        const effectiveValue = remainingOverrides.get(p.name) ?? p.value;
        const reason = validateParam(effectiveValue, def);
        if (!reason) continue;
        const entry = `${p.name}=${effectiveValue} (${reason})`;
        if (acknowledgedInvalid.has(p.name)) acknowledged.push(entry);
        else invalids.push(entry);
      }
      const lines = [
        "# Generated by AIR6 Param Filter",
        `# Date: ${date}`,
        fileName ? `# Source: ${fileName}` : null,
        `# Filter: ${activeListName}`,
        `# Applied: ${remainingParams.length} params | Protected (removed): ${protectedParams.length} params`,
        invalids.length > 0 ? `# Invalid values: ${invalids.join(", ")}` : null,
        acknowledged.length > 0 ? `# Acknowledged (user-reviewed): ${acknowledged.join(", ")}` : null,
        "#",
      ].filter(Boolean);
      header = lines.join("\n") + "\n";
    }
    onConfirm(header);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />

      <div className="relative z-10 w-full max-w-sm rounded-xl border border-border bg-card shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border bg-toolbar px-5 py-3.5">
          <div className="flex items-center gap-2">
            <Download className="h-4 w-4 text-primary" />
            <h2 className="text-sm font-bold text-foreground">Save Filtered File</h2>
          </div>
          <button
            onClick={onClose}
            className="rounded p-1.5 text-muted-foreground hover:bg-secondary hover:text-foreground transition-colors cursor-pointer"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Stats */}
        <div className="px-5 py-4 flex flex-col gap-2.5">
          <StatRow
            value={protectedParams.length}
            label="params filtered out (protected)"
            colorClass="text-red-400"
          />
          <StatRow
            value={remainingParams.length}
            label="params will be written"
            colorClass="text-applied-text"
          />
          {invalidCount > 0 && (
            <StatRow
              value={invalidCount}
              label="invalid values"
              colorClass="text-red-400"
            />
          )}
          {acknowledgedCount > 0 && (
            <StatRow
              value={acknowledgedCount}
              label="acknowledged by user"
              colorClass="text-blue-400"
            />
          )}
          {modifiedCount > 0 && (
            <StatRow
              value={modifiedCount}
              label="value overrides"
              colorClass="text-amber-400"
            />
          )}
        </div>

        {/* Metadata toggle */}
        <div className="border-t border-border px-5 py-3">
          <label className="flex items-center gap-2 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={includeHeader}
              onChange={(e) => setIncludeHeader(e.target.checked)}
              className="h-3.5 w-3.5 rounded accent-foreground cursor-pointer"
            />
            <span className="text-sm text-foreground">Include metadata header</span>
          </label>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 border-t border-border bg-toolbar px-5 py-3">
          <button
            onClick={onClose}
            className="rounded-md border border-border px-4 py-2 text-sm text-foreground hover:bg-secondary transition-colors cursor-pointer"
          >
            Cancel
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors cursor-pointer"
          >
            <Download className="h-3.5 w-3.5" />
            Download File
          </button>
        </div>
      </div>
    </div>
  );
}
